[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "claudius"
author = "Zoïs Moitier"
author-email = "z.moitier@gmail.com"
home-page = "https://pypi.org/project/claudius/"
classifiers = ["License :: OSI Approved :: MIT License"]
description-file = "README.md"
requires-python = '>=3.7'
requires = [
    "numba", "numpy", "matplotlib", "scipy"
]

